 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Control;
import Model.DB;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Student
 */
public class Home extends javax.swing.JFrame {

    boolean modal;
    Control c= new Control();
    String usr;
    /**
     * Creates new form Home
     */
    public Home() {
        
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Graphics/icon.png")));
        comfl.setModel(new javax.swing.DefaultComboBoxModel(new String[] 
        {"ID", "Book Name", "Author", "Category", "ISBN No", "Availability","All"}));
        Tbl1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION );

    }
    public void incom(String unm){
        lblus.setText(unm);
        usr=unm;
    }
    //Tablel row adding
    
    ///$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
     private javax.swing.JLabel utxt;
     
    public javax.swing.JLabel getUtext(String nm,boolean en) {
         Btnen(en,nm);
         
         if(en==true){
            lblbc.setText("Books : "+String.valueOf(c.cBk()));
            lblmem.setText("Members : "+String.valueOf(c.cMem()));
         }
        return null;
         
       
    }

   public javax.swing.JTable clrmT() {
        udTbl();
        return null;
    }
    
    public void setUtext(javax.swing.JLabel utxt) {
        this.lblus = utxt;
    }
    public void Btnen(boolean enbl,String txt){
        
        this.btnco.setEnabled(enbl);
        this.btnci.setEnabled(enbl);
        this.btnnb.setEnabled(enbl);
        this.btnnm.setEnabled(enbl);
        this.btnum.setEnabled(enbl);
        this.btnsum.setEnabled(enbl);
        this.opbk.setEnabled(enbl);
        this.opme.setEnabled(enbl);
        this.txtschbr.setEditable(enbl);
        this.btnsch.setEnabled(enbl);
        this.comfl.setEnabled(enbl);
        clrmT();
        this.lblus.setText("User : "+txt);
        usr=txt;
        Maction.setEnabled(enbl);
        
        if(enbl==true){
            Mlogout.setText("Log out");
            btnlgout.setText("Log out");
        
        }
        
    }
    public void setLogBText(String txt){
        btnlgout.setText(txt);
        Mlogout.setText(txt);
   }
    ///$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bGroup1 = new javax.swing.ButtonGroup();
        jMenuItem2 = new javax.swing.JMenuItem();
        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        jPanel1 = new javax.swing.JPanel();
        btnci = new javax.swing.JButton();
        btnco = new javax.swing.JButton();
        btnnm = new javax.swing.JButton();
        btnum = new javax.swing.JButton();
        btnsum = new javax.swing.JButton();
        btnnb = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnlgout = new javax.swing.JButton();
        btnex = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnsch = new javax.swing.JButton();
        txtschbr = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comfl = new javax.swing.JComboBox();
        opbk = new javax.swing.JRadioButton();
        opme = new javax.swing.JRadioButton();
        jlist = new javax.swing.JLabel();
        lblus = new javax.swing.JLabel();
        lblbc = new javax.swing.JLabel();
        lblmem = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl1 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        lblst = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Mlogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Mexit = new javax.swing.JMenuItem();
        Maction = new javax.swing.JMenu();
        mCo = new javax.swing.JMenuItem();
        mCi = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mNb = new javax.swing.JMenuItem();
        mNm = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mUs = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mSum = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuAbout = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("D-Library");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setName("dlib"); // NOI18N
        setState(72);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnci.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Graphics/check_out.png"))); // NOI18N
        btnci.setText("Check-In  ");
        btnci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnciActionPerformed(evt);
            }
        });

        btnco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Graphics/check_in.png"))); // NOI18N
        btnco.setText("Check-Out");
        btnco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncoActionPerformed(evt);
            }
        });

        btnnm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnnm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Graphics/addm.png"))); // NOI18N
        btnnm.setText("New Member");
        btnnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnmActionPerformed(evt);
            }
        });

        btnum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Graphics/users.png"))); // NOI18N
        btnum.setText("User Manage");
        btnum.setToolTipText("");
        btnum.setActionCommand("Users Maneger");
        btnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnumActionPerformed(evt);
            }
        });

        btnsum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Graphics/sum.png"))); // NOI18N
        btnsum.setText("Summary");
        btnsum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsumMouseClicked(evt);
            }
        });
        btnsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumActionPerformed(evt);
            }
        });

        btnnb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnnb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Graphics/add.png"))); // NOI18N
        btnnb.setText("New Book");
        btnnb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnnb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnnm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnci)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnnb)
                .addGap(12, 12, 12)
                .addComponent(btnnm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnum)
                .addGap(9, 9, 9)
                .addComponent(btnsum)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        btnlgout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnlgout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Graphics/logO.png"))); // NOI18N
        btnlgout.setText("Login");
        btnlgout.setToolTipText("");
        btnlgout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlgoutActionPerformed(evt);
            }
        });

        btnex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Graphics/exit.png"))); // NOI18N
        btnex.setText("Exit      ");
        btnex.setToolTipText("Exit");
        btnex.setFocusable(false);
        btnex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnlgout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlgout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnex, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jPanel5.setBackground(new java.awt.Color(0, 153, 204));

        btnsch.setBackground(new java.awt.Color(102, 102, 102));
        btnsch.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnsch.setForeground(new java.awt.Color(255, 255, 255));
        btnsch.setText("Search");
        btnsch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnschActionPerformed(evt);
            }
        });

        txtschbr.setBorder(null);

        jPanel6.setBackground(new java.awt.Color(0, 153, 204));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Filter By");

        comfl.setBackground(new java.awt.Color(153, 153, 153));
        comfl.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        comfl.setForeground(new java.awt.Color(255, 255, 255));
        comfl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comfl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comflActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(comfl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comfl))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtschbr, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtschbr, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsch))
                .addContainerGap())
        );

        opbk.setBackground(new java.awt.Color(0, 153, 204));
        bGroup1.add(opbk);
        opbk.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        opbk.setForeground(new java.awt.Color(255, 255, 255));
        opbk.setSelected(true);
        opbk.setText("Books");
        opbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opbkActionPerformed(evt);
            }
        });

        opme.setBackground(new java.awt.Color(0, 153, 204));
        bGroup1.add(opme);
        opme.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        opme.setForeground(new java.awt.Color(255, 255, 255));
        opme.setText("Members");
        opme.setToolTipText("");
        opme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opmeActionPerformed(evt);
            }
        });

        jlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Graphics/logo.jpg"))); // NOI18N

        lblus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Graphics/user.jpg"))); // NOI18N
        lblus.setText("User :");
        lblus.setToolTipText("User");
        lblus.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblbc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Graphics/bq.jpg"))); // NOI18N
        lblbc.setText("Books : ");
        lblbc.setToolTipText("Total of books");
        lblbc.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblbc.setAutoscrolls(true);

        lblmem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Graphics/mm.jpg"))); // NOI18N
        lblmem.setText("Members : ");
        lblmem.setToolTipText("Total of members");
        lblmem.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblmem.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jlist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(opbk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(lblus, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblbc, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmem, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlist)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opbk, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opme, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblus)
                            .addComponent(lblbc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblmem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), new java.awt.Color(153, 153, 153)));

        Tbl1.setAutoCreateRowSorter(true);
        Tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Book Name", "Author", "Category", "ISBN No", "Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tbl1.setName(""); // NOI18N
        Tbl1.getTableHeader().setReorderingAllowed(false);
        Tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl1);
        Tbl1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (Tbl1.getColumnModel().getColumnCount() > 0) {
            Tbl1.getColumnModel().getColumn(0).setResizable(false);
            Tbl1.getColumnModel().getColumn(1).setResizable(false);
            Tbl1.getColumnModel().getColumn(2).setResizable(false);
            Tbl1.getColumnModel().getColumn(3).setResizable(false);
            Tbl1.getColumnModel().getColumn(4).setResizable(false);
            Tbl1.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1067, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setFloatable(false);
        jToolBar1.setFocusable(false);
        jToolBar1.add(lblst);

        jMenu1.setText("File");

        Mlogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        Mlogout.setText("Log out");
        Mlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MlogoutActionPerformed(evt);
            }
        });
        jMenu1.add(Mlogout);
        jMenu1.add(jSeparator1);

        Mexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        Mexit.setText("Exit");
        Mexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MexitActionPerformed(evt);
            }
        });
        jMenu1.add(Mexit);

        jMenuBar1.add(jMenu1);

        Maction.setText("Action");

        mCo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mCo.setText("Check-Out");
        mCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCoActionPerformed(evt);
            }
        });
        Maction.add(mCo);

        mCi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        mCi.setText("Check-In");
        mCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCiActionPerformed(evt);
            }
        });
        Maction.add(mCi);
        Maction.add(jSeparator2);

        mNb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mNb.setText("New Book");
        mNb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNbActionPerformed(evt);
            }
        });
        Maction.add(mNb);

        mNm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mNm.setText("New Member");
        mNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNmActionPerformed(evt);
            }
        });
        Maction.add(mNm);
        Maction.add(jSeparator3);

        mUs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mUs.setText("User Manage");
        mUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUsActionPerformed(evt);
            }
        });
        Maction.add(mUs);
        Maction.add(jSeparator4);

        mSum.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mSum.setText("Summary");
        mSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSumActionPerformed(evt);
            }
        });
        Maction.add(mSum);

        jMenuBar1.add(Maction);

        jMenu3.setText("Help");

        mnuAbout.setText("About");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        jMenu3.add(mnuAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1280, 751));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexActionPerformed
      
        int result = JOptionPane.showConfirmDialog(this,"Are you sure you want to exit?", "Exit",JOptionPane.YES_NO_OPTION);

        if(result==0){
            System.exit(WindowConstants.EXIT_ON_CLOSE); 
        }
        
    }//GEN-LAST:event_btnexActionPerformed

    private void btnnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnmActionPerformed
        RegisterStudent Rf=new RegisterStudent(this,true,false);
        Rf.setTitle("Add New Member");
        Rf.uMode(false);
        Rf.setVisible(true);
        
//  new RegisterStudent(this,true).setVisible(true);
    }//GEN-LAST:event_btnnmActionPerformed

    private void btnlgoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlgoutActionPerformed
        lblus.setText("User : ");
        lblbc.setText("Books : ");
        lblmem.setText("Members : ");
        Mlogout.setText("Login");
        btnlgout.setText("Login");

        new Login(this,true).setVisible(true);   
       
    }//GEN-LAST:event_btnlgoutActionPerformed

    private void btnnbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnbActionPerformed
        new Regbook(this,true,false).setVisible(true);
    }//GEN-LAST:event_btnnbActionPerformed

    private void btnsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumActionPerformed
            new sum(this,true).setVisible(true);
    }//GEN-LAST:event_btnsumActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    
      int result = JOptionPane.showConfirmDialog(this,"Are you sure you want to exit?", "Exit",JOptionPane.YES_NO_OPTION);

        if(result==0){
            System.exit(WindowConstants.EXIT_ON_CLOSE); 
        }
         
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    public void SimpleHeaderRenderer() {
        setFont(new Font("Consolas", Font.BOLD, 14));
        setForeground(Color.BLUE);
        //setBorder(BorderFactory.createEtchedBorder());
    }

    private void MlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MlogoutActionPerformed
       btnlgoutActionPerformed(evt);
    }//GEN-LAST:event_MlogoutActionPerformed

    private void MexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MexitActionPerformed
        btnexActionPerformed(evt);
    }//GEN-LAST:event_MexitActionPerformed

    private void mCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCoActionPerformed
       btncoActionPerformed(evt);
    }//GEN-LAST:event_mCoActionPerformed

    private void btncoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncoActionPerformed

      new Checkout(this,true,false).setVisible(true);

    }//GEN-LAST:event_btncoActionPerformed

    private void btnciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnciActionPerformed
       new Checkout(this,true,true).setVisible(true);
    }//GEN-LAST:event_btnciActionPerformed

    private void mCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCiActionPerformed
        btnciActionPerformed(evt);
    }//GEN-LAST:event_mCiActionPerformed

    private void mNbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNbActionPerformed
        btnnbActionPerformed(evt);
    }//GEN-LAST:event_mNbActionPerformed

    private void mNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNmActionPerformed
        btnnmActionPerformed(evt);
    }//GEN-LAST:event_mNmActionPerformed

    private void mUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUsActionPerformed
      btnumActionPerformed(evt);
    }//GEN-LAST:event_mUsActionPerformed

    private void btnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnumActionPerformed
       
        new Users(this,true,usr).setVisible(true);
        
    }//GEN-LAST:event_btnumActionPerformed

    private void mSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSumActionPerformed
        btnsumActionPerformed(evt);
    }//GEN-LAST:event_mSumActionPerformed

    private void btnschActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnschActionPerformed
       udTbl();
        if(opbk.isSelected()){   
            schBook();
        }
        else
        {
            schMem();
        }
        lblst.setText(Tbl1.getRowCount()+" result(s) found");
    }//GEN-LAST:event_btnschActionPerformed
    public void udTbl(){
        DefaultTableModel model = (DefaultTableModel)Tbl1.getModel();

        while(model.getRowCount() > 0){
            for(int i = 0 ; i < model.getRowCount();i++){
                model.removeRow(i);
                
         }
        }
        lblst.setText("");
    }
    private void schBook(){
        
              String st=  txtschbr.getText();
            try{
                  
                Connection con = DB.createConnection();
                
                Statement stmt = con.createStatement();
                
                ResultSet rs=null ;
                
                //String ctext=comfl.getSelectedItem().toString();
                int x=comfl.getSelectedIndex();
                
                if(st.equals("*")){
                    rs = stmt.executeQuery("SELECT * FROM book_data");
                }
                else{
                    if(x==0){
                        rs = stmt.executeQuery("SELECT * FROM book_data WHERE id='"+st+"'");
                    }
                    else if(x==1){
                         rs = stmt.executeQuery("SELECT * FROM book_data WHERE name='"+st+"'");
                    }
                    else if(x==2){
                        rs = stmt.executeQuery("SELECT * FROM book_data WHERE auth='"+st+"'");
                    }
                    else if(x==3){
                         rs = stmt.executeQuery("SELECT * FROM book_data WHERE cat='"+st+"'");
                    }   
                    else if(x==4){
                        rs = stmt.executeQuery("SELECT * FROM book_data WHERE isbn='"+st+"'");
                    }
                    else if(x==5){
                        rs = stmt.executeQuery("SELECT * FROM book_data WHERE avbl='"+st+"'");
                    }
                else{
                     rs = stmt.executeQuery("SELECT * FROM book_data");
                    }
                }
                
                
             while(rs.next())
             {
                 String bid=rs.getString("id");
                 String nm=rs.getString("name");
                 String auth=rs.getString("auth");
                 String cat=rs.getString("cat");
                 String isbn=rs.getString("isbn");
                 String avb=rs.getString("avbl");
                 
               DefaultTableModel model = (DefaultTableModel) Tbl1.getModel();
               Object[] row = {bid, nm, auth,cat ,isbn,avb};
                model.setRowCount(model.getRowCount());
                model.addRow(row);
                this.Tbl1.setModel(model);
             }  
                 
              }
              catch(Exception e){
                  
              }
    }
        private void schMem(){
            
            String st=  txtschbr.getText();
            
        try{
                  
                Connection con = DB.createConnection();
                
                Statement stmt = con.createStatement();
                
                ResultSet rs =null;
                
                int x=comfl.getSelectedIndex();
                if(st.equals("*")){
                    rs = stmt.executeQuery("SELECT * FROM studata");
                }
                else{
                    if(x==0){
                        rs = stmt.executeQuery("SELECT * FROM studata WHERE id='"+st+"'");
                    }
                    else if(x==1){
                        rs = stmt.executeQuery("SELECT * FROM studata WHERE inm='"+st+"'");
                    }
                    else if(x==2){
                        rs = stmt.executeQuery("SELECT * FROM studata WHERE nm='"+st+"'");
                    }
                    else if(x==3){
                        rs = stmt.executeQuery("SELECT * FROM studata WHERE nic='"+st+"'");
                    }
                    else if(x==4){
                        rs = stmt.executeQuery("SELECT * FROM studata WHERE gen='"+st+"'");
                    }
                    else{
                        rs = stmt.executeQuery("SELECT * FROM studata");
                    }
                }
                
             while(rs.next())
             {
                 String id=rs.getString("id");
                 String inm=rs.getString("inm");
                 String nm=rs.getString("nm");
                 String nic=rs.getString("nic");
                 String adr=rs.getString("adr");
                 String gen=rs.getString("gen");
                 
               DefaultTableModel model = (DefaultTableModel) Tbl1.getModel();
               Object[] row = {id, inm,nm,nic ,adr,gen};
                model.setRowCount(model.getRowCount());
                model.addRow(row);
                this.Tbl1.setModel(model);
                
             }  
                 
              }
              catch(Exception e){
                  
              }
        
    }
        
    private void opbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opbkActionPerformed
       
        comfl.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"ID", "Book Name", "Author", "Category", "ISBN No", "Availability"}));
        Tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                    "ID", "Book Name", "Author", "Category", "ISBN No", "Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lblst.setText("");
    }//GEN-LAST:event_opbkActionPerformed

    private void opmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opmeActionPerformed
        comfl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Index No", "Student Name", "NIC", "Gender"}));
        
        Tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                    "ID", "Index No", "Student Name", "NIC", "Address", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lblst.setText("");
    }//GEN-LAST:event_opmeActionPerformed

    private void comflActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comflActionPerformed
        
    }//GEN-LAST:event_comflActionPerformed

    private void Tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl1MouseClicked
    
      int mc=evt.getClickCount();
     
      if (mc>1){
       
          int n= Tbl1.getSelectedRow();
      
            DefaultTableModel model = (DefaultTableModel)Tbl1.getModel();
            String md= model.getValueAt(n, 0).toString();//model.getValueAt(n, 0).toString();

            if (opbk.isSelected()){
                //System.out.println(md);
               Regbook rb= new Regbook(this,true,true);
               rb.sDt(Integer.parseInt(md));
               rb.setTitle("Book ID : "+md);
                rb.setVisible(true);
            }
            else{
                RegisterStudent rs= new RegisterStudent(this,true,true);
                rs.sDt(Integer.parseInt(md));
                rs.setTitle("Student ID : "+md);
                rs.setVisible(true);
            }
      }

    }//GEN-LAST:event_Tbl1MouseClicked

    private void btnsumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsumMouseClicked

    }//GEN-LAST:event_btnsumMouseClicked

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        new about(this,true).setVisible(true);
    }//GEN-LAST:event_mnuAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Home F=new Home();
               F.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Maction;
    private javax.swing.JMenuItem Mexit;
    private javax.swing.JMenuItem Mlogout;
    private javax.swing.JTable Tbl1;
    private javax.swing.ButtonGroup bGroup1;
    private javax.swing.JButton btnci;
    private javax.swing.JButton btnco;
    private javax.swing.JButton btnex;
    private javax.swing.JButton btnlgout;
    private javax.swing.JButton btnnb;
    private javax.swing.JButton btnnm;
    private javax.swing.JButton btnsch;
    private javax.swing.JButton btnsum;
    private javax.swing.JButton btnum;
    private javax.swing.JComboBox comfl;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jlist;
    private javax.swing.JLabel lblbc;
    private javax.swing.JLabel lblmem;
    private javax.swing.JLabel lblst;
    private javax.swing.JLabel lblus;
    private javax.swing.JMenuItem mCi;
    private javax.swing.JMenuItem mCo;
    private javax.swing.JMenuItem mNb;
    private javax.swing.JMenuItem mNm;
    private javax.swing.JMenuItem mSum;
    private javax.swing.JMenuItem mUs;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JRadioButton opbk;
    private javax.swing.JRadioButton opme;
    private javax.swing.JTextField txtschbr;
    // End of variables declaration//GEN-END:variables

   
}
