/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Control;
import Model.DB;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class RegisterStudent extends javax.swing.JDialog {
                String gen="";
    /**
     * Creates new form RegisterStudent
     */
    Control c= new Control();
    public RegisterStudent(java.awt.Frame parent, boolean modal,boolean eM) {
        
        super(parent, modal);
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Graphics/null.png")));
        txtad.setText(this.getTitle());
        
         uMode(eM);
    }
    private void setUi(){
                
                int bc=0;
                int in=0;
                boolean x=false;
                
                in=c.cMem()+1;
           
            try{
                
            Connection con  = DB.createConnection();
            
            Statement stmt = con.createStatement();
            
            do{    
                ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM studata WHERE id='"+in+"'");
     
                rs.next();
                bc=rs.getInt(1);
            
                if(bc>0){
                    in=in+1;
                }
                else{
                    x=true;
                }
                }while(x==false);
       
                lblid.setText(String.valueOf(in));
            
            }
            catch(Exception e)
            {
            System.out.println(e.getMessage());
            }
       
    }
    public void uMode(boolean umod){
        if(umod==true){
            btnSub.setEnabled(false);
        }
        else{
            
            btnDel.setEnabled(false);
            btnedit.setEnabled(false);
            btnSub.setText("Submit");
            btnokcan.setText("Cancel");
            setUi();
        }
    }
    
    public void sDt(int index){
    
        try{
            Connection con  = DB.createConnection();
            
            Statement stmt = con.createStatement();
                
            ResultSet rs = stmt.executeQuery("SELECT * FROM studata WHERE id='"+index+"'");
    
           //id,inm,nm,nic,adr,mail,gen,con,idt,rdt
            tEnbl(false);
            
            while(rs.next())
             {
                lblid.setText(rs.getString("id"));
                txtind.setText(rs.getString("inm"));
                txtnm.setText(rs.getString("nm"));
                txtnic.setText(rs.getString("nic"));
                txtad.setText(rs.getString("adr"));
                txtcn.setText(rs.getString("con"));
                txtml.setText(rs.getString("mail"));
                
                gen=rs.getString("gen");
                
                if(gen.equals("Male")){
                    gml.setSelected(true);
                    gfl.setEnabled(false);
                }
                else{
                    gfl.setSelected(true);
                    gml.setEnabled(false);
                }
             }  
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }
    private void tEnbl(boolean en){
            
            //lblid.setEditable(en);
            txtind.setEditable(en);
            txtnm.setEditable(en);
            txtnic.setEditable(en);
            txtad.setEditable(en);
            txtcn.setEditable(en);
            txtml.setEditable(en);
            gml.setEnabled(true);
            gfl.setEnabled(true);

            
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnm = new javax.swing.JTextField();
        txtml = new javax.swing.JTextField();
        txtad = new javax.swing.JTextField();
        gml = new javax.swing.JRadioButton();
        gfl = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtcn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtind = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        btnSub = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnokcan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Student ID ");

        jLabel2.setText("Address");

        jLabel3.setText("E-mail");

        jLabel4.setText("Gender");

        txtnm.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        gml.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(gml);
        gml.setText("Male");
        gml.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                gmlStateChanged(evt);
            }
        });
        gml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmlActionPerformed(evt);
            }
        });

        gfl.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(gfl);
        gfl.setText("Female");
        gfl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gflItemStateChanged(evt);
            }
        });

        jLabel5.setText("Contact");

        txtcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnActionPerformed(evt);
            }
        });
        txtcn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcnKeyReleased(evt);
            }
        });

        jLabel6.setText("Name");

        jLabel7.setText("NIC No");

        txtind.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtindFocusLost(evt);
            }
        });
        txtind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtindKeyReleased(evt);
            }
        });

        jLabel8.setText("Index No");

        lblid.setBackground(new java.awt.Color(102, 102, 102));
        lblid.setText("001");

        btnSub.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSub.setText("Update");
        btnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubActionPerformed(evt);
            }
        });

        btnDel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnedit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnokcan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnokcan.setText("  OK   ");
        btnokcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokcanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtind, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(gml)
                                .addGap(18, 18, 18)
                                .addComponent(gfl))
                            .addComponent(txtml, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnm, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnic)
                            .addComponent(txtad)
                            .addComponent(txtcn, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnokcan)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(gml)
                    .addComponent(gfl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDel)
                    .addComponent(btnSub)
                    .addComponent(btnokcan)
                    .addComponent(btnedit))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(371, 325));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnKeyReleased
        
        if(!txtcn.getText().isEmpty()){
         
            for(int i=0; i < txtcn.getText().length() ; i++){
                char c= txtcn.getText().charAt(i);
                    if(!Character.isDigit(c)){
                        String s=txtcn.getText().substring(0,i);
                        txtcn.setText(null);
                        txtcn.setText(s);
                    }
            }
        }
    }//GEN-LAST:event_txtcnKeyReleased

    private void btnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubActionPerformed

        if(btnSub.getText().equals("Submit")){
            snw();  
        }
        else{
            upd();
            btnokcan.setText("  OK   ");
        }
        c.clMt();
    }//GEN-LAST:event_btnSubActionPerformed
    
    
    
    private void snw (){
                try{

                    
            if(gml.isSelected()){
                gen="Male";
            }
            else if(gfl.isSelected()){
                gen="Female";
            }

            if(txtnm.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Name Cannot be Empty");
            }
                
            Connection con  = DB.createConnection();
            
            Statement stmt = con.createStatement();
                
            ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM studata");
     
            rs.next();
            
            //int rowCount = rs.getInt(1);
            
            String SQL="INSERT INTO studata (id,inm,nm,nic,adr,mail,gen,con) VALUES(?,?,?,?,?,?,?,?)";
            
            PreparedStatement pstmt  = con.prepareStatement(SQL);

            pstmt.setString(1, lblid.getText());
            pstmt.setString(2, txtind.getText());
            pstmt.setString(3, txtnm.getText());
            pstmt.setString(4, txtnic.getText());
            pstmt.setString(5, txtad.getText());
            pstmt.setString(6, txtml.getText());
            pstmt.setString(7, gen);
            pstmt.setString(8, txtcn.getText());

            pstmt.executeUpdate();
            pstmt.close();

           JOptionPane.showMessageDialog(this,"Data sucsesfuly submited","Submit",JOptionPane.INFORMATION_MESSAGE);

           lblid.setText("");
           txtind.setText("");
           txtnm.setText("");
           txtnic.setText("");
           txtad.setText("");
           txtcn.setText("");
           txtml.setText("");
           
           lblid.setText(String.valueOf(c.cMem()+1));

        }

        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
        private void upd (){
            
            try{
                    
            if(gml.isSelected()){
                gen="Male";
            }
            else if(gfl.isSelected()){
                gen="Female";
            }

            if(txtnm.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Name Cannot be Empty");
            }
            
            int nid= Integer.parseInt(lblid.getText());
            
            Connection con  = DB.createConnection();
            
            Statement stmt = con.createStatement();
            //studata ,inm,nm,nic,adr,mail,gen,con,
            
            stmt.executeUpdate("update studata set inm='"+txtind.getText()+"' where id='"+nid+"'");
            stmt.executeUpdate("update studata set nm='"+txtnm.getText()+"' where id='"+nid+"'");
            stmt.executeUpdate("update studata set nic='"+txtnic.getText()+"' where id='"+nid+"'");
            stmt.executeUpdate("update studata set adr='"+txtad.getText()+"' where id='"+nid+"'");
            stmt.executeUpdate("update studata set mail='"+txtml.getText()+"' where id='"+nid+"'");
            stmt.executeUpdate("update studata set gen='"+gen+"' where id='"+nid+"'");
            stmt.executeUpdate("update studata set con='"+txtcn.getText()+"' where id='"+nid+"'");    
            
            JOptionPane.showMessageDialog(this,"Data sucsesfuly updated","Edit",JOptionPane.INFORMATION_MESSAGE);
                
                tEnbl(false);
                btnSub.setEnabled(false);
                btnedit.setEnabled(true);
                btnDel.setEnabled(true);

                if(gen.equals("Male")){
                    gml.setSelected(true);
                    gfl.setEnabled(false);
                }
                else{
                    gfl.setSelected(true);
                    gml.setEnabled(false);
                }

        }

        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        int result = JOptionPane.showConfirmDialog(this,"Are you sure you want to delete?", "Delete",JOptionPane.YES_NO_OPTION);
                int nid= Integer.parseInt(lblid.getText());
        if(result==0){
            
            try{
                Connection con = DB.createConnection();
                Statement stmt = con.createStatement();
                stmt.executeUpdate("delete from studata WHERE id='"+nid+"'"); 
                JOptionPane.showMessageDialog(this,"Recode sucsesfuly deleted","Delete",JOptionPane.INFORMATION_MESSAGE);
                c.clMt();
                this.dispose();
            }
            catch(Exception e){
            }
            }
    }//GEN-LAST:event_btnDelActionPerformed
    
    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
                tEnbl(true);
                btnSub.setEnabled(true);
                btnedit.setEnabled(false);
                btnDel.setEnabled(false);
                btnokcan.setText("Cancel");
    }//GEN-LAST:event_btneditActionPerformed

    private void gmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gmlActionPerformed

    private void gmlStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gmlStateChanged
        
    }//GEN-LAST:event_gmlStateChanged

    private void gflItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gflItemStateChanged
       
        
    }//GEN-LAST:event_gflItemStateChanged

    private void txtcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnActionPerformed

    private void txtindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtindKeyReleased
        
        if(!txtind.getText().isEmpty()){
         
            for(int i=0; i < txtind.getText().length() ; i++){
                char c= txtind.getText().charAt(i);
                    if(!Character.isDigit(c)){
                        String s=txtind.getText().substring(0,i);
                        txtind.setText(null);
                        txtind.setText(s);
                    }
            }
        }
    }//GEN-LAST:event_txtindKeyReleased

    private void txtindFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtindFocusLost
        //System.out.println("lf");
         if(btnSub.getText().equals("Submit")){
            try{
                
                Connection con  = DB.createConnection();
                Statement stmt = con.createStatement();
                
                ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM studata WHERE inm='"+txtind.getText()+"'");
     
                rs.next();
                int bc=0;
                bc=rs.getInt(1);
                
                    if(bc>0){
                        JOptionPane.showMessageDialog(this,"The index number already exist!","",JOptionPane.WARNING_MESSAGE);
                        btnSub.setEnabled(false);
                    }
                    else{
                        btnSub.setEnabled(true);
                    }
                }
                
            catch(Exception e)
            {
            //System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_txtindFocusLost

    private void btnokcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokcanActionPerformed
        if(btnokcan.getText().equals("Cancel")){
            if(btnSub.getText().equals("Submit")){
                 this.dispose();
            }    
            else{
                btnokcan.setText("  OK   ");     
                tEnbl(false);
                btnSub.setEnabled(false);
                btnedit.setEnabled(true);
                btnDel.setEnabled(true);
            }
        }
        else{
                this.dispose();
        }
        
    }//GEN-LAST:event_btnokcanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterStudent dialog = new RegisterStudent(new javax.swing.JFrame(), true,false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnSub;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnokcan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton gfl;
    private javax.swing.JRadioButton gml;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextField txtad;
    private javax.swing.JTextField txtcn;
    private javax.swing.JTextField txtind;
    private javax.swing.JTextField txtml;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtnm;
    // End of variables declaration//GEN-END:variables
}
