/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Model.DB;
import java.awt.Frame;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Admin
 */
public class Users extends javax.swing.JDialog{
  String cun;          
    /**
     * Creates new form Users
     */
    public Users(java.awt.Frame parent, boolean modal, String un) {
        super(parent, modal);
        initComponents();
        //this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Graphics/null.png")));
        cun=un;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtnun = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtp1 = new javax.swing.JPasswordField();
        txtp2 = new javax.swing.JPasswordField();
        btnnu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtnp2 = new javax.swing.JPasswordField();
        txtnp1 = new javax.swing.JPasswordField();
        txtopwd = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btncp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Manage");

        jLabel6.setText("User Name");

        jLabel7.setText("Password");

        jLabel8.setText("Retype-Password");

        btnnu.setText("Add New User");
        btnnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Delete user acount (!)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Old Password");

        jLabel4.setText("New Password");

        jLabel5.setText("Retype-New Password");

        btncp.setText("Change Password");
        btncp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(43, 43, 43)
                        .addComponent(txtnun, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(49, 49, 49)
                        .addComponent(txtp1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(txtp2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnnu))
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(54, 54, 54)
                        .addComponent(txtopwd, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(49, 49, 49)
                        .addComponent(txtnp1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addComponent(txtnp2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btncp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(txtopwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(txtnp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtnp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btncp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(txtnun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(txtp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnnu))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncpActionPerformed
                String Duser= "";
                String Dpass= "";
        try{
           
                Connection con = DB.createConnection();
                
                Statement stmt = con.createStatement();
                
                ResultSet rs = stmt.executeQuery("SELECT * FROM logdta WHERE uname = '"+cun+"'");
     
             while(rs.next())
             {
                 Dpass = rs.getString("pword");
                 
             }
             
                if (Dpass.equals(txtopwd.getText().toString())){
                    
                    if(txtnp1.getText().toString().equals(txtnp2.getText().toString()) && !txtnp1.getText().toString().equals("")){
                 
                        try{
                            stmt.executeUpdate("update logdta set pword='"+txtnp1.getText().toString()+"' WHERE uname = '"+cun+"'");        
                            JOptionPane.showMessageDialog(this,"Password changed succeed!","Change Password",JOptionPane.INFORMATION_MESSAGE);
                            txtnp1.setText("");
                            txtnp2.setText("");
                            txtopwd.setText("");
                        }
                        catch(Exception e){
                            
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"New passwords doesn't match or empty","Change Password",JOptionPane.ERROR_MESSAGE);
                        txtnp1.setText("");
                        txtnp2.setText("");
                    }
                    
                 }
              
              else
              {
                 
                  JOptionPane.showMessageDialog(this,"Old password is invalid","Change Password",JOptionPane.ERROR_MESSAGE);
                  txtopwd.setText("");
              }
             
       }
       catch(Exception e){
           
       }
    }//GEN-LAST:event_btncpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            try{
           
                Connection con = DB.createConnection();
                
                Statement stmt = con.createStatement();
                
                ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM logdta");
     
                rs.next();
                int rC= rs.getInt(1);
                
                if(rC>1){
                    
                //}
                int result = JOptionPane.showConfirmDialog(this,"This operation cannot undo. Are you sure you want to Delete this User?", "Exit",JOptionPane.YES_NO_OPTION);
                
                if(result==0){
                    
                stmt.executeUpdate("delete from logdta WHERE uname = '"+cun+"'");
                
                   for (Frame frame : Frame.getFrames()) {
                      if (frame.getName().equals("dlib")) {
                        Home Hm=(Home)frame;
                        Hm.getUtext("",false);
                        Hm.setLogBText("Login");
                      }
                  }
                
                        // new MainWindow(Home,true).setVisible(true); 
                        this.dispose();
                        
                JOptionPane.showMessageDialog(this,"User account deleted","User Delete",JOptionPane.INFORMATION_MESSAGE);
                }
                
                }
                else{
                    JOptionPane.showMessageDialog(this,"This user can't delete. System have only one user.","User Delete",JOptionPane.WARNING_MESSAGE);
                }
                
            }
            catch(Exception e){
                
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuActionPerformed
        // TODO add your handling code here:
        if(txtp1.getText().toString().equals(txtp2.getText().toString()) && !txtp1.getText().toString().equals(""))
        {
            
        String unm="";
        try{
           
                Connection con = DB.createConnection();
                
                Statement stmt = con.createStatement();
                
                ResultSet rs = stmt.executeQuery("SELECT * FROM logdta WHERE uname = '"+txtnun.getText()+"'");
     
             while(rs.next())
             {
                 unm = rs.getString("uname");
                 
             }

             
             if (unm.equals("")){
                 
                String SQL="INSERT INTO logdta(uname,pword) VALUES (?,?)";
                PreparedStatement pstmt  = con.prepareStatement(SQL);

                pstmt.setString(1, txtnun.getText());
                pstmt.setString(2, txtp1.getText().toString());
                
                pstmt.executeUpdate();
                pstmt.close();
                
                 JOptionPane.showMessageDialog(this,"New user add succeed!","Add new user",JOptionPane.INFORMATION_MESSAGE);
                 
                 txtnun.setText("");
                 txtp1.setText("");
                 txtp2.setText("");
                
             }
             
             else{
                JOptionPane.showMessageDialog(this,"User name already available, use another name","Add new user",JOptionPane.WARNING_MESSAGE);
                
             }
             
             
            }
             catch(Exception e){
                     System.out.print(e);
                     }
        }
        else
        {
                JOptionPane.showMessageDialog(this,"New passwords doesn't match or empty","Add new user",JOptionPane.ERROR_MESSAGE);
                txtp1.setText("");
                txtp2.setText("");
        }
        
    }//GEN-LAST:event_btnnuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 Users dialog = new Users(new javax.swing.JFrame(), true,null);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncp;
    private javax.swing.JButton btnnu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField txtnp1;
    private javax.swing.JPasswordField txtnp2;
    private javax.swing.JTextField txtnun;
    private javax.swing.JPasswordField txtopwd;
    private javax.swing.JPasswordField txtp1;
    private javax.swing.JPasswordField txtp2;
    // End of variables declaration//GEN-END:variables
}
